/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as JoinRouteImport } from './routes/join'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AuthRoleRouteImport } from './routes/auth.$role'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems.$problemId'
import { Route as UniversityIndexRouteImport } from './routes/university.index'
import { Route as UniversityTeamsRouteImport } from './routes/university.teams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/$role',
  path: '/auth/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/problems/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityIndexRoute = UniversityIndexRouteImport.update({
  id: '/university/',
  path: '/university/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityTeamsRoute = UniversityTeamsRouteImport.update({
  id: '/university/teams',
  path: '/university/teams',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industry': typeof IndustryRoute
  '/join': typeof JoinRoute
  '/ngo': typeof NgoRoute
  '/team': typeof TeamRoute
  '/auth/$role': typeof AuthRoleRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/university/teams': typeof UniversityTeamsRoute
  '/problems/': typeof ProblemsIndexRoute
  '/university/': typeof UniversityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industry': typeof IndustryRoute
  '/join': typeof JoinRoute
  '/ngo': typeof NgoRoute
  '/team': typeof TeamRoute
  '/auth/$role': typeof AuthRoleRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/university/teams': typeof UniversityTeamsRoute
  '/problems': typeof ProblemsIndexRoute
  '/university': typeof UniversityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industry': typeof IndustryRoute
  '/join': typeof JoinRoute
  '/ngo': typeof NgoRoute
  '/team': typeof TeamRoute
  '/auth/$role': typeof AuthRoleRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/university/teams': typeof UniversityTeamsRoute
  '/problems/': typeof ProblemsIndexRoute
  '/university/': typeof UniversityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/government'
    | '/how-it-works'
    | '/industry'
    | '/join'
    | '/ngo'
    | '/team'
    | '/auth/$role'
    | '/problems/$problemId'
    | '/university/teams'
    | '/problems/'
    | '/university/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/government'
    | '/how-it-works'
    | '/industry'
    | '/join'
    | '/ngo'
    | '/team'
    | '/auth/$role'
    | '/problems/$problemId'
    | '/university/teams'
    | '/problems'
    | '/university'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/government'
    | '/how-it-works'
    | '/industry'
    | '/join'
    | '/ngo'
    | '/team'
    | '/auth/$role'
    | '/problems/$problemId'
    | '/university/teams'
    | '/problems/'
    | '/university/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRoute
  GovernmentRoute: typeof GovernmentRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustryRoute: typeof IndustryRoute
  JoinRoute: typeof JoinRoute
  NgoRoute: typeof NgoRoute
  TeamRoute: typeof TeamRoute
  AuthRoleRoute: typeof AuthRoleRoute
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  UniversityTeamsRoute: typeof UniversityTeamsRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
  UniversityIndexRoute: typeof UniversityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo': {
      id: '/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof NgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$role': {
      id: '/auth/$role'
      path: '/auth/$role'
      fullPath: '/auth/$role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/': {
      id: '/university/'
      path: '/university'
      fullPath: '/university/'
      preLoaderRoute: typeof UniversityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/teams': {
      id: '/university/teams'
      path: '/university/teams'
      fullPath: '/university/teams'
      preLoaderRoute: typeof UniversityTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRoute,
  GovernmentRoute: GovernmentRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustryRoute: IndustryRoute,
  JoinRoute: JoinRoute,
  NgoRoute: NgoRoute,
  TeamRoute: TeamRoute,
  AuthRoleRoute: AuthRoleRoute,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  UniversityTeamsRoute: UniversityTeamsRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
  UniversityIndexRoute: UniversityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
